inseven/statuspanel

ios/StatusPanel/Config.swift, ios/StatusPanel/Fonts.swift, ios/StatusPanel/View Controllers/PrivacyModeController.swift, ios/StatusPanel/View Controllers/SettingsViewController.swift, ios/StatusPanel/ViewController.swift
This change updates the settings view controller to support setting the title font and body font independently. It also removes the special-case code which magically selected a title font for fonts which didn't perform well as title fonts; we now trust users to figure that out on their own.
=> feat(ios): Select the title font

scripts/environment.sh
Following an update to Xcode 13, there seem to be problems with the built-in Ruby and Python installs. This change ensures the relevant Homebrew locations are on the path so we can use these instead.
=> ci: Ensure the Homebrew copy of Ruby and Python on the path

scripts/build.sh
Unfortunately we now need to use two different versions of Xcode for iOS and macOS builds. This change selects the Xcode specified by the `IOS_XCODE_PATH` environment variable configured on the runner.
=> ci(ios): Select the shipping version of Xcode before building

ios/StatusPanel/Data/DummyDataSource.swift, ios/StatusPanel/Data/National Rail/NationalRailDataSource.swift
Since it only applies to a font we don't generally use for the body
text any more anyway, and looks bad in the fonts we _do_ use (ie
guicons and unifont-16)
=> fix(ios): Remove font-specific workaround from NationalRailDataSource

ios/StatusPanel/BitmapFontLabel.swift
The change to saving and restoring the context state caused us to only show a redacted block for the last word of each line.
=> fix(ios): Fix regression in redact words

ios/StatusPanel/Data/DummyDataSource.swift, ios/StatusPanel/Fonts.swift, ios/StatusPanel/ViewController.swift
Previously it was hard-coded to 10, now use half the line height.
Meaning for unifont-16, this reduces the inter-item gap to 8 pixels,
which I think looks better.
Also made 10px be the maximum so that unifont-32 doesn't look overly
spaced out.
Also made DummyDataSource honour showIcons as oftentimes showing all
the special chars in one big block isn't that useful and showIcons
offers a convenient way of hiding that for testing.
Before:
After:
@jbmorley what do you think? It's not all that noticeable unless you flick between them but unifont-16 has felt slightly too spacious for me since we added it.
=> fix(ios): Tighten line spacing on unifont-16

ios/StatusPanel/View Controllers/SettingsViewController.swift
The 'About StatusPanel' button in settings should follow the convention that an ellipsis is used whenever a new sheet will be presented.
=> fix(ios): Update 'About StatusPanel' button text

Pipfile, ios/ExportOptions.plist, nodemcu/Pipfile, scripts/build.sh, scripts/install-dependencies.sh
This also includes a drive-by fix to use the action runner's built-in GitHub CLI instead of installing one as part of the build process, and disables bitcode upload.
=> fix: Update various Pipfiles to name the sources

service/app.py, service/tests/test_api.py
This change is intended to make it easier to generate good unique identifiers for devices by allowing canonical UUIDs as identifiers.
=> feat(service): Support UUID identifiers

simulator/StatusPanel Simulator/ApplicationModel.swift, simulator/StatusPanel Simulator/ContentView.swift, simulator/StatusPanel Simulator/DeviceIdentifier.swift, simulator/StatusPanel Simulator/Service.swift
This change also includes a drive-by fix to use the new v3 endpoint.
=> fix(mac-simulator): Generate unique identifiers for each simulator instance

.github/workflows/build-website.yaml, .gitignore
This includes a drive-by fix to ensure we actually deploy the simulator in website builds.
=> ci: Rename website build job

architecture.md, simulator/StatusPanel Simulator/Extensions/Data.swift
This includes a drive-by documentation fix to clarify the pixel color values.
=> fix(simulator-mac): Use the project accent color for the panel highlight color

ios/StatusPanel/Data/DataSourceController.swift
Unfortunately the National Rail proxy we were using is no longer supported; disabling until we have an alternative.
=> fix(ios): Disable National Rail data source

device/python/device.py
This change makes use of signals to simulate select-like behavior and schedule updates on the main thread even though key events are dispatched by RPi.GPIO on a background thread.
It relies on the `append` operation being atomic under the global interpreter lock to schedule operations on an event queue (`tasks`) from interrupt handlers which are then safely consumed by the main thread when normal execution resumes.
=> feat(device-python): Toggle images by pressing the 'A' button

ios/StatusPanel.xcodeproj/project.pbxproj, ios/StatusPanel/BitmapFontLabel.swift, ios/StatusPanel/Config.swift, ios/StatusPanel/Data/DataSource.swift, ios/StatusPanel/Data/LabelStyle.swift, ios/StatusPanel/Extensions/UILabel.swift, ios/StatusPanel/RedactMode.swift, ios/StatusPanel/Renderer.swift, ios/StatusPanel/View Controllers/SettingsViewController.swift, ios/StatusPanel/View Controllers/ViewController.swift
This change moves the render methods out of `ViewController` and into static methods on a new `Renderer` struct with a view to ultimately moving device update management out of the view controller instance. This should allow renders when the full UI stack isn't present and decouple device updates from UI, making it easier to support multiple device configurations in the future.
=> refactor(ios): Move rendering out of `ViewController`

ios/StatusPanel.xcodeproj/project.pbxproj, ios/StatusPanel/AppDelegate.swift, ios/StatusPanel/Config.swift, ios/StatusPanel/Data/DataSourceController.swift, ios/StatusPanel/Device.swift, ios/StatusPanel/Service.swift, ios/StatusPanel/View Controllers/SettingsViewController.swift, ios/StatusPanel/View Controllers/ViewController.swift
This change goes some way to consolidating the process of update generation and upload with a view to moving it out into a dedicated device manager. It also starts to address thread-safety issues when accessing settings through the `Config` class and makes tentative steps towards new async code.
=> refactor(ios): Consolidate update generation and upload

simulator/macos/StatusPanel Simulator/Service.swift
This change honors the header length reported in the header to ensure it is compatible with future header updates.
=> fix(simulator-mac): Future-proof update handling

ios/StatusPanel/Data/DataSource.swift, ios/StatusPanel/Utilities/Localization.swift, ios/StatusPanel/View Controllers/DarkModeController.swift, ios/StatusPanel/View Controllers/SettingsViewController.swift, ios/StatusPanel/Views/FlagsSection.swift
This change includes a drive-by fix to rename the localisation methods to `Localized` to match the platform conventions.
=> refactor(ios): Use SwiftUI `Picker` for the item style selection

ios/StatusPanel/View Controllers/AddDataSourceController.swift, ios/StatusPanel/View Controllers/SettingsViewController.swift
This change moves the work of updating the data sources into `AddDataSourceController` to allow it to be more easily reused in different places in the app. This change lays the groundwork for per-device layout management.
=> refactor(ios): Update data sources directly within `AddDataSourceController`

ios/StatusPanel/Data/Calendar/CalendarDataSource.swift
I missed a change when allowing per-instance calendar settings meaning that the calendar instances were still displaying the globally selected calendars.
=> fix(ios): Use the per-instance calendar selection in the calendar data source

ios/StatusPanel/Views/SettingsView.swift
The device identifier is available in the device settings view meaning we no longer need it in the main devices list.
=> fix(ios): Don't show the device identifier in the devices list

ios/StatusPanel/AppDelegate.swift, ios/StatusPanel/Data/DataSource.swift, ios/StatusPanel/PixelRenderer.swift, ios/StatusPanel/Views/FlagsSection.swift, ios/StatusPanel/en-GB.lproj/Localizable.strings, ios/StatusPanel/en.lproj/Localizable.strings
We were incorrectly inserting a vertical divider whenever we saw the 'spans columns' flag _even_ if we were in single-column mode. This change fixes that bug and renames the 'Prefers New Column' option to 'Prefers New Section' to acknowledge that it will add a divider in both single- and two-column mode.
=> fix(ios): Show a horizontal divider in single-column mode

ios/StatusPanel/Views/IntroductionView.swift
This is a development feature and is unnecessarily confusing for regular users.
=> fix(ios): Disable 'Add From Clipboard' in release builds

ios/StatusPanel/AppDelegate.swift
This was much more important when the device list wasn't part of the main UI. The experience will be improved further when we address https://github.com/inseven/statuspanel/issues/576.
=> fix(ios): Don't show alert when adding new devices

ios/StatusPanel.xcodeproj/project.pbxproj, ios/StatusPanel/Config.swift, ios/StatusPanel/Extensions/UIImage.swift, ios/StatusPanel/Utilities/DataView.swift, ios/StatusPanel/Views/AddDeviceView.swift, ios/StatusPanel/Views/ContentView.swift, ios/StatusPanel/Views/DeviceDetailView.swift, ios/StatusPanel/Views/IntroductionView.swift, ios/StatusPanel/Views/SettingsView.swift
This change adds the ability to export preview images using the share sheet. It also includes a small drive-by refactor that moves `DataView` into its own file, and renames 'Show Debug Information' to 'Show Developer Tools'.
=> feat(ios): Export preview images

ios/StatusPanel/Config.swift
This change also includes a drive-by fix to correctly namespace device settings.
=> fix(ios): Clean up orphaned device and data source settings

service/ansible/ansible.cfg, service/package/prerm
This includes a drive-by fix to disable cowboy in the Ansible configuration.
=> fix(service): Fix image clean up when removing Debian packages

service/web/src/static/index.html
Update the title to 'StatusPanel Service', and add an explicit 'Copyright' to the copyright string.
=> fix(service): Small copy tweaks to the status page

.github/workflows/build-app.yaml, .gitmodules
This change updates the iOS app GitHub Actions workflow to a matrix build in anticipation of a new macOS release following WWDC 2023. We'll use the GitHub-provided macOS 13 runner for release allowing us to transition the self-hosted runner to macOS [presumably] 14.
=> ci(ios): Build on GitHub Actions builders and self-hosted builders

device/nodemcu/README.markdown, device/nodemcu/src/init.lua, device/nodemcu/src/main.lua
On the S3 anyway, there's no need to do an initial ping, and not doing it means you can boot the board (to non-auto mode) without needing the screen to be connected.
=> fix(firmware): Don't require Inky to be attached in order to init

.github/workflows/build-app.yaml, ios/ExportOptions.plist, ios/StatusPanel/Service.swift, scripts/build.sh
This change updates the tests to use the iPhone 15 Pro simulator and adopts async/await for the inner upload implementation to address an error-turned-warning when calling `MainActor` isolated code from the main queue.
=> ci: Update the builds for Xcode 15

.github/workflows/build-app.yaml
I forgot to update the release check to stop checking against the matrix build name.
=> ci: Update the iOS workflow to automatically generate releases

ios/StatusPanel/BitmapFontLabel.swift, ios/StatusPanel/Controls/FontLabelTableViewCell.swift, ios/StatusPanel/Device.swift, ios/StatusPanel/Extensions/UILabel.swift, ios/StatusPanel/PixelRenderer.swift, ios/StatusPanel/Views/FontView.swift
For now, this ignores colors the inky can't handle directly, such as purple.
=> feat(ios): Colorise characters whose unicode names include colors we can represent

.github/workflows/build-website.yaml, .gitignore, docs/_config.yml, scripts/build-website.sh
This changes uses GitHub actions 'new' support for custom pages builds to deploy directly rather than going via a documentation branch. This makes it much easier to git ignore intermediate website build files so we don't mistakenly check them in locally and paves the way to adding a Jekyll plugin so it can generate release notes (and perhaps even the simulator) itself.
=> ci: Don't check website builds into a separate branch

service/README.markdown, service/web/src/static/index.html
StatusPanel is no longer published by InSeven so we don't need the footer anymore.
=> service: Update the API page to remove InSeven from the footer

.github/workflows/build.yaml
This change temporarily disables failing Raspberry Pi builds---I don't have time to figure out what's going wrong at the moment.
=> ci: Disable Raspberry Pi builds

.github/workflows/build.yaml
This change uses `.tool-versions` via mise-en-place to pin Python to 3.10.11 as required by the esp32 nodemcu firmware builds.
=> ci: Use Python 3.10 for esp32 firmware builds

.github/workflows/build.yaml
It looks like the version of `cmake` that now comes with Ubuntu has dropped support for the the declared format used by the esp32 `CMakeLists.txt` 🤦🏻‍♂️. This change simply disables the firmware builds as I don’t have the time to look into it at the moment.
=> ci: Disable esp32 firmware builds
